markdown: kramdown

kramdown:
  syntax_highlighter: rouge

permalink: pretty

title: Andrew Etter
description: I manage developer documentation teams and am the bestselling author of <a href="https://www.amazon.com/Modern-Technical-Writing-Introduction-Documentation-ebook/dp/B01A2QL9SS">Modern Technical Writing</a>.
url: http://andyetter.com
disclaimer: All views are my own and do not reflect those of my employer.

main_stylesheet: main.css
favicon: favicon.png

google_analytics: UA-90655047-1

author:
  name: Andrew Etter
  linkedin: https://www.linkedin.com/in/andrew-etter-0a013349

paginate: 4

plugins:
  - jekyll-paginate
